"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 00:56:26.592538

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_label', sa.String(length=255), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=64), nullable=False),
    sa.Column('redirect_uris', sa.JSON(), nullable=False),
    sa.Column('webhook_url', sa.String(length=1024), nullable=True),
    sa.Column('webhook_secret', sa.String(length=128), nullable=False),
    sa.Column('send_transaction_events', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_target_id'), 'audit_log', ['target_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('accounts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=10), nullable=False),
    sa.Column('account_type', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('allow_overdraft', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_index(op.f('ix_accounts_customer_id'), 'accounts', ['customer_id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_application_id'), 'consents', ['application_id'], unique=False)
    op.create_index(op.f('ix_consents_customer_id'), 'consents', ['customer_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payment_id', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_response_body', sa.Text(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_application_id'), 'webhook_deliveries', ['application_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_payment_id'), 'webhook_deliveries', ['payment_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_status'), 'webhook_deliveries', ['status'], unique=False)
    op.create_table('authorization_codes',
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('consent_id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('redirect_uri', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['consent_id'], ['consents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code_hash')
    )
    op.create_index(op.f('ix_authorization_codes_consent_id'), 'authorization_codes', ['consent_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('consent_id', sa.String(length=32), nullable=False),
    sa.Column('debtor_account_id', sa.String(length=32), nullable=False),
    sa.Column('creditor_account_number', sa.String(length=10), nullable=False),
    sa.Column('creditor_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reference', sa.String(length=35), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_reason', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('redirect_uri', sa.String(length=1024), nullable=True),
    sa.Column('journal_id', sa.String(length=32), nullable=True),
    sa.Column('process_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('authorised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['consent_id'], ['consents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['debtor_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'idempotency_key', name='uq_payments_idempotency')
    )
    op.create_index(op.f('ix_payments_application_id'), 'payments', ['application_id'], unique=False)
    op.create_index(op.f('ix_payments_consent_id'), 'payments', ['consent_id'], unique=False)
    op.create_index(op.f('ix_payments_debtor_account_id'), 'payments', ['debtor_account_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('consent_id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['consent_id'], ['consents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_tokens_code_hash'), 'tokens', ['code_hash'], unique=False)
    op.create_index(op.f('ix_tokens_consent_id'), 'tokens', ['consent_id'], unique=False)
    op.create_table('journals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.String(length=35), nullable=True),
    sa.Column('payment_id', sa.String(length=32), nullable=True),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('journal_id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.String(length=35), nullable=True),
    sa.Column('counterparty_name', sa.String(length=255), nullable=False),
    sa.Column('counterparty_account_number', sa.String(length=10), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq')
    )
    op.create_index('ix_transactions_account_seq', 'transactions', ['account_id', 'seq'], unique=False)
    op.create_index(op.f('ix_transactions_journal_id'), 'transactions', ['journal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_journal_id'), table_name='transactions')
    op.drop_index('ix_transactions_account_seq', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('journals')
    op.drop_index(op.f('ix_tokens_consent_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_code_hash'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_debtor_account_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_consent_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_application_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_authorization_codes_consent_id'), table_name='authorization_codes')
    op.drop_table('authorization_codes')
    op.drop_index(op.f('ix_webhook_deliveries_status'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_payment_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_application_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_consents_customer_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_application_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_accounts_customer_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('customers')
    op.drop_index(op.f('ix_audit_log_target_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('applications')
    # ### end Alembic commands ###
